### ISSUE TITLE
misspelling

### ISSUE THREAD

**Issue by Wjxfi** [v1tzor/TimePlanner#18]
![8759e7fa-fa9a-4c3a-92e3-062e83075257.jpg](https://github.com/v1tzor/TimePlanner/assets/113500363/2f13c994-cd1d-4721-9122-74e716139ad0)

@IzzySoft

**Comment by IzzySoft** [comment]
Fixed with the next sync, thanks!

May I recommend setting up Fastlane structures here, so the authors themselves can control how their app is presented? I gladly provide a "starter package" with what I've set up in my repo currently – and there's always my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance. Changes would then be pulled along with each new release.

**Comment by IzzySoft** [comment]
@v1tzor so would you accept my offer, or consider the idea of having Fastlane established here?

**Comment by v1tzor** [comment]
I'll set up Fastlane later

**Comment by IzzySoft** [comment]
OK, thanks! Please also remember to increase `versionCode` with each release – seems like you forgot this time:

    Binary files /web/ftp/repo/fdroid/repo/ru.aleshin.timeplanner_5.apk and /web/ftp/repo/fdroid/repo/ru.aleshin.timeplanner_0.4.0-beta.apk differ

This means the current release has the same `versionCode` (`5`) as the previous one already used, so whoever already has the p installed won't receive any update notification for this release.
