### ISSUE TITLE
Please adding the "notifications" permission (for the alerts)

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#48]
![1000042026](https://github.com/v1tzor/TimePlanner/assets/113377431/8462f8be-c0a8-4ad4-b5e1-c5f54e990425)

![1000042028](https://github.com/v1tzor/TimePlanner/assets/113377431/0cdc235e-3965-4cf5-b700-71f7bb12a5cf)

**Comment by Ammar-Ishfaq** [comment]
@serrq  I've added the notification permission under pull request #49 

Below is the ScreenShot of how it looks to the user:
![image](https://github.com/v1tzor/TimePlanner/assets/54596139/62e8bf13-f64f-4baa-8ea9-a94f71e6a4ab)

**Comment by Ammar-Ishfaq** [comment]
could you please share more about the permissions page?
Is it the system or the in-app?

**Comment by Ammar-Ishfaq** [comment]
Okay got it "We need to take the user there for full control of notification permission access."
Will update as mentioned above reference to screenshot

**Comment by Ammar-Ishfaq** [comment]
@serrq Both app scenarios are using an **identical** approach you can verify this using the below links 

### Reference: 
**SimpleX chat**: 
https://github.com/v1tzor/TimePlanner/assets/54596139/86c9c5e8-c92f-40e1-9d77-e438917067f9
AND
**TimePlannerApp:** 
https://github.com/v1tzor/TimePlanner/assets/54596139/82c81aa2-ba6a-4a7e-859a-a484d3b6ca5a


**Note**:
I've noticed that you didn't allow notification permission in order to get into the notification details including notification categories, reference to your first screenshot in chat: https://github.com/v1tzor/TimePlanner/issues/48#issuecomment-1744699360.

**Device specs**:
Samsung galaxy a13 
Android 13

However, feel free to test the build using the Notification PR code
If there are any queries feel free to ask

Happy coding

**Comment by Ammar-Ishfaq** [comment]
Can you kindly guide me that the above screenshot is from the pull I created?

**Comment by Ammar-Ishfaq** [comment]
Here's the quick build [link](https://we.tl/t-y6QV4ipVkh) you can use to test and verify.
However, you can also take the pull and then test the build.

**Comment by Ammar-Ishfaq** [comment]
okay, got it.
You will be able to see changes officially once the contributor merged pull request #49
